allprojects/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('bookmyhotel/', include('bookmyhotel.urls')),
    path('shopmart/', include('shopmart.urls')),
    path('expensetracker/', include('expensetracker.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, reverse_lazy
from . import views

from .forms import LoginForm, MyPasswordResetForm, MySetPasswordForm
from django.contrib.auth import views as authView

app_name = 'core'

urlpatterns = [
    path('', views.welcome_page, name='welcome_page'),

    path('signup/', views.signup, name='signup'),

    path('login/', authView.LoginView.as_view(
        template_name = 'core/login_form.html',
        authentication_form = LoginForm
    ), name='login'),

    path('logout/', authView.LogoutView.as_view(), name='logout'),

    path('password-reset/', authView.PasswordResetView.as_view(
        template_name='core/password_reset.html',
        email_template_name='core/password_reset_email.html',
        form_class=MyPasswordResetForm,
        success_url= reverse_lazy('core:password_reset_done')
    ), name='password_reset'),

    path('password-reset-done/', authView.PasswordResetDoneView.as_view(
        template_name='core/password_reset_done.html'
    ), name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', authView.PasswordResetConfirmView.as_view(
        template_name='core/password_reset_confirm.html',
        form_class=MySetPasswordForm,
        success_url = reverse_lazy('core:password_reset_complete')
    ), name='password_reset_confirm'),

    path('password-reset-complete/', authView.PasswordResetCompleteView.as_view(
        template_name='core/password_reset_complete.html'
    ), name='password_reset_complete'),
]

expensetracker/urls.py
from django.urls import path

from expensetracker import views


app_name = 'expensetracker'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('new/', views.new, name='new'),
    path('analytics/', views.analytics, name='analytics'),
    path('list/', views.list, name='list'),
    path('incomes/', views.incomes, name='incomes'),
    path('expenses/', views.expenses, name='expenses'),
    path('analytics-data/', views.analytics_data, name='analytics_data'),
    path('chart-data/', views.chart_data, name='chart_data'),
]

expensetracker/models.py
from django.db import models
from core.models import User

# Create your models here.

class TransactionTypes(models.TextChoices):
    INCOME = 'IN', 'Income'
    EXPENSE = 'EX', 'Expense'

class Category(models.Model):
    name = models.CharField(max_length=191)
    created_by = models.ForeignKey(User, related_name='categories', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ('name',)

class Transaction(models.Model):
    category = models.ForeignKey(Category, related_name='transactions', on_delete=models.SET_NULL, blank=True, null=True)
    new_category = models.CharField(max_length=191, blank=True)
    name = models.CharField(max_length=191)
    type = models.CharField(max_length=2, choices=TransactionTypes.choices, default=TransactionTypes.INCOME)
    notes = models.TextField(max_length=191, blank=True, null=True)
    amount = models.FloatField()
    created_by = models.ForeignKey(User, related_name='transactions', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name}--{self.category.name}--{self.type}--{self.amount}"
    
    class Meta:
        ordering = ('created_at',)

expensetracker/forms.py
from django import forms

from .models import Transaction

input_classes = 'w-full py-4 px-6 rounded-xl bg-teal-100 text-black'

class NewTransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ('name', 'notes', 'category', 'new_category','type' , 'amount')
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': 'Name of your transaction',
                'class': input_classes,
            }),

            'notes': forms.TextInput(attrs={
                'placeholder': 'Add a simple note',
                'class': input_classes,
            }),

            'category': forms.Select(attrs={
                'placeholder': 'Choose a category',
                'class': input_classes,
            }),

            'new_category': forms.TextInput(attrs={
                'placeholder': 'Enter a new category',
                'class': input_classes,
            }),

            'type': forms.Select(attrs={
                'class': input_classes,
            }),

            'amount': forms.TextInput(attrs={
                'placeholder': 'Enter amount',
                'class': input_classes,
            }),
        }

    def clean(self):
        cleaned_data = super().clean()
        category = cleaned_data.get('category')
        new_category = cleaned_data.get('new_category')

        if not category and not new_category:
            raise forms.ValidationError("Either 'category' or 'new_category' must be filled.")
        
        return cleaned_data

expensetracker/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from collections import defaultdict

from .models import Transaction, Category
from .forms import NewTransactionForm

# Create your views here.
@login_required
def chart_data(request):
    transactions = Transaction.objects.filter(created_by = request.user)

    income_amounts = [income.amount for income in transactions if income.type == 'IN']
    income_values = []
    total_income = 0

    for amount in income_amounts:
        total_income += amount
        income_values.append(total_income)
    
    expense_amounts = [expense.amount for expense in transactions if expense.type == 'EX']
    expense_values = []
    total_expense = 0
    
    for amount in expense_amounts:
        total_expense += amount
        expense_values.append(total_expense)

    labels = [transaction.created_at.strftime('%d-%m-%Y') for transaction in transactions]

    chart_data = {
        'label': 'Income-Expense Chart',
        'labels': labels,

        'income_values': income_values,
        'expense_values': expense_values,

        'chart_type': 'areaspline',
    }

    return JsonResponse(chart_data)



def dashboard(request):
    if request.user.is_authenticated:
        transactions = Transaction.objects.filter(created_by = request.user).order_by('-created_at')
        recent_history = transactions[:5]
    else:
        transactions = None

    if transactions:
        total_income = 0
        total_expense = 0

        income_category_totals = defaultdict(float)
        expense_category_totals = defaultdict(float)

        for transaction in transactions:

            if transaction.type == 'IN':
                total_income += transaction.amount
                income_category_totals[transaction.category] += transaction.amount

            elif transaction.type == 'EX':
                total_expense += transaction.amount
                expense_category_totals[transaction.category] += transaction.amount

        total_balance = total_income - total_expense
        
        
        highest_income_category = max(income_category_totals, key=income_category_totals.get, default=None)
        lowest_income_category = min(income_category_totals, key=income_category_totals.get, default=None)

        highest_expense_category = min(expense_category_totals, key=expense_category_totals.get, default=None)
        lowest_expense_category = max(expense_category_totals, key=expense_category_totals.get, default=None)    

    else:
        return redirect('expensetracker:new')
                
    return render(request, 'expensetracker/dashboard.html', {
        'recent_history': recent_history,
        'total_income': round(total_income, 2),
        'total_expense': round(total_expense, 2),
        'total_balance': round(total_balance, 2),

        'highest_income_category': highest_income_category,
        'lowest_income_category': lowest_income_category,

        'highest_expense_category': highest_expense_category,
        'lowest_expense_category': lowest_expense_category,

    })

@login_required
def new(request):
    if request.method == 'POST':
        form = NewTransactionForm(request.POST)

        if form.is_valid():
            transaction = form.save(commit=False)

            category = form.cleaned_data['category']
            new_category = form.cleaned_data['new_category']

            if not category and new_category:
                category = Category.objects.create(name=new_category, created_by=request.user)

            transaction.category = category
            transaction.created_by = request.user
            transaction.save()

            return redirect('expensetracker:dashboard')
    else:
        form = NewTransactionForm()

    return render(request, 'expensetracker/form.html', { 'form': form })

login_required
def analytics_data(request):
    transactions = Transaction.objects.filter(created_by = request.user)

    if transactions:
        income_category_totals = defaultdict(float)
        expense_category_totals = defaultdict(float)

        for transaction in transactions:

            if transaction.type == 'IN':
                income_category_totals[transaction.category] += transaction.amount

            elif transaction.type == 'EX':
                expense_category_totals[transaction.category] += transaction.amount
        
        income_category_total_labels = []
        for income_category_total in income_category_totals:
            income_category_total_labels.append(income_category_total.name)

        expense_category_total_labels = []
        for expense_category_total in expense_category_totals:
            expense_category_total_labels.append(expense_category_total.name)
        
        income_category_total_amounts = []
        for income_category_total in income_category_totals:
            amount = income_category_totals[income_category_total]
            income_category_total_amounts.append(amount)

        expense_category_total_amounts = []
        for expense_category_total in expense_category_totals:
            amount = expense_category_totals[expense_category_total]
            expense_category_total_amounts.append(amount)
        

    chart_data = {
        'title': 'Analytics',

        'income_category_labels': income_category_total_labels,
        'income_category_totals': income_category_total_amounts,

        'expense_category_labels': expense_category_total_labels,
        'expense_category_totals': expense_category_total_amounts
    }

    return JsonResponse(chart_data)

login_required
def analytics(request):
    return render(request, 'expensetracker/analytics.html', {'title': 'Analytics'})


@login_required
def list(request):
    transactions = Transaction.objects.filter(created_by=request.user).order_by('-created_at')
    return render(request, 'expensetracker/list.html', {
        'transactions': transactions,
    })

@login_required
def incomes(request):
    incomes = Transaction.objects.filter(created_by=request.user).filter(type = 'IN').order_by('-created_at')
    return render(request, 'expensetracker/incomes.html', {
        'incomes': incomes,
    })

@login_required
def expenses(request):
    expenses = Transaction.objects.filter(created_by=request.user).filter(type = 'EX').order_by('-created_at')
    return render(request, 'expensetracker/expenses.html', {
        'expenses': expenses,
    })

expensetracker/templates/expensetracker/analytics.html
{% extends 'expensetracker/base.html' %}


{% block head %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.0/chart.min.js"></script>
{% endblock %}


{% block title %} {{ title }}  {% endblock %}


{% block content %}
<div class="w-full md:h-full flex flex-col justify-center">
    <h1 class="mb-5 text-center p-5 text-3xl text-emerald-600 font-semibold">Analytics</h1>

    <div class="w-5/6 mx-auto flex flex-col md:flex-row gap-12 ">

        <div class="md:w-1/2 bg-emerald-800 rounded-3xl">
            <canvas id="income-container"></canvas>
        </div>

        <div class="md:w-1/2 bg-red-500 rounded-3xl">
            <canvas id="expense-container"></canvas>
        </div>
        
    </div>

</div>
{% endblock %}


{% block scripts %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        
        // Fetch data from your Django backend
        fetch('/expensetracker/analytics-data/')
            .then((response) => response.json())
            .then((data) => {
                Chart.defaults.color = '#000'
                Chart.defaults.font.size = 12

                /* Income Analytics graph */
                var income_ctx = document.getElementById('income-container');
                var income_data = {
                    labels: data.income_category_labels,
                    datasets: [{
                        label: 'Income In Basis of Categories',
                        data: data.income_category_totals,
                        fill: true,
                        backgroundColor: 'rgba(21, 128, 61, 0.2)',
                        borderColor: 'rgb(21, 128, 61)',
                        pointBackgroundColor: 'rgb(21, 128, 61)',
                        pointBorderColor: '#fff',
                        pointHoverBackgroundColor: '#000',
                        pointHoverBorderColor: 'rgb(255, 99, 132)'
                    }]
                };
                var income_config = {
                        type: 'radar',
                        data: income_data,
                        options: {
                            elements: {
                                line: {
                                    borderWidth: 3
                                }
                            },
                            scale: {
                                r: {
                                    angleLines: {
                                        display: false
                                    },
                                    suggestedMin: 50,
                                    suggestedMax: 100,
                                    pointLabels: { // This section controls the font for the category labels
                                        font: {
                                            weight: 'light'
                                        },
                                    }
                                }
                            },
                            plugins: {
                                legend: {
                                    display: true,
                                    labels: {
                                        color: '#000',
                                        font: {
                                            size: 16,
                                            weight: 'bold'
                                        }
                                    } 
                                }
                            },
                        },
                    };
                var myChart = new Chart(income_ctx, income_config);


                /* Expense Analytics graph */
                var expense_ctx = document.getElementById('expense-container');
                var expense_data = {
                    labels: data.expense_category_labels,
                    datasets: [{
                        label: 'Expense In Basis of Categories',
                        data: data.expense_category_totals,
                        fill: true,
                        backgroundColor: 'rgba(153, 27, 27, .2)',
                        borderColor: 'rgb(153 27 27)',
                        pointBackgroundColor: 'rgb(153 27 27)',
                        pointBorderColor: '#fff',
                        pointHoverBackgroundColor: '#000',
                        pointHoverBorderColor: 'rgb(255, 99, 132)'
                    }]
                };
                var expense_config = {
                        type: 'radar',
                        data: expense_data,
                        options: {
                            elements: {
                                line: {
                                    borderWidth: 3
                                }
                            },
                            scale: {
                                r: {
                                    angleLines: {
                                        display: false
                                    },
                                    suggestedMin: 50,
                                    suggestedMax: 100,
                                    pointLabels: { // This section controls the font for the category labels
                                        font: {
                                            weight: 'light',
                                        },
                                    }
                                }
                            },
                            plugins: {
                                legend: {
                                    display: true,
                                    labels: {
                                        color: '#000',
                                        font: {
                                            size: 16,
                                            weight: 'bold'
                                        }
                                    } 
                                }
                            },
                        },
                    };
                var myChart = new Chart(expense_ctx, expense_config);
                
            });
    });
</script>
{% endblock %}

expensetracker/templates/expensetracker/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    {% block head %}
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css" rel="stylesheet">
    <title>{% block title %}{% endblock %} | Tracker</title>
</head>
<body class="h-screen bg-gray-600 bg-teal-950 flex">

    <nav id="navbar" class="h-full hidden lg:block z-10 w-[300px] h-full py-5 px-5 rounded-xl bg-emerald-950">

        <div id="profile" class="mb-5 p-4 rounded-xl flex justify-even align-items gap-5 bg-emerald-800 border border-black">
                <img src="{% static 'expensetracker/images/user_photo.jpg' %}" alt="profile-photo" class="h-14 rounded-full border border-black">
                <div>
                    <h1 class="text-xl text-black font-bold">{{request.user.name}}</h1>
                    <a href="{% url 'expensetracker:dashboard' %}"><p class="text-xl font-semibold">ExpTracker</p></a>
                </div>
        </div>

        <div id="catalog" class="text-xl font-semibold whitespace-nowrap p-4 border border-black flex flex-col items-start gap-5 rounded-xl bg-emerald-800">
            
            <a href="{% url 'expensetracker:dashboard' %}" class="hover:scale-95 transition duration-300 ease-in-out {% if request.path == '/' %} scale-95 text-gray-800 {% endif %}">Dashboard</a>
            <a href="{% url 'expensetracker:analytics' %}" class="hover:scale-95 transition duration-300 ease-in-out {% if request.path == '/transactions/analytics/' %} scale-95 text-gray-800 {% endif %}">Analytics</a>
            <a href="{% url 'expensetracker:new' %}" class="hover:scale-95 transition duration-300 ease-in-out {% if request.path == '/transactions/new/' %} scale-95 text-gray-800 {% endif %}">New Transaction</a>
            <a href="{% url 'expensetracker:list' %}" class="hover:scale-95 transition duration-300 ease-in-out {% if request.path == '/transactions/list/' %} scale-95 text-gray-800 {% endif %}">All Transactions</a>
            <a href="{% url 'expensetracker:incomes' %}" class="hover:scale-95 transition duration-300 ease-in-out {% if request.path == '/transactions/incomes/' %} scale-95 text-gray-800 {% endif %}">Incomes</a>
            <a href="{% url 'expensetracker:expenses' %}" class="hover:scale-95 transition duration-300 ease-in-out {% if request.path == '/transactions/expenses/' %} scale-95 text-gray-800 {% endif %}">Expenses</a>
            
        </div>

        <div class="p-4 absolute bottom-4">
            {% if request.user.is_authenticated %}
            <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-red-500 text-stale-200 rounded-xl hover:bg-red-600 border border-black">Logout</a>
            {% else %}
            <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-emerald-800 text-stale-200 rounded-xl hover:bg-emerald-900 border border-black">LogIn</a>
            <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-emerald-800 text-stale-200 rounded-xl hover:bg-emerald-900 border border-black">SignUp</a>
            {% endif %}

        </div>

    </nav>

    <div id="menu_icon" class="absolute top-5 left-8 lg:hidden z-10">
        <button class="scale-125 hover:scale-150 font-bold transition duration-300 ease-in-out" onclick="toggleMenu()"><i class="ri-menu-line"></i></button>
    </div>

    <div class="w-full lg:max-w-7xl h-full xl:w-10/12 mx-auto my-auto p-4 rounded-xl lg:flex lg:items-center" onclick="hideMenu()">
        {% block content %}

        {% endblock %}
    </div>

    {% block scripts %}
    
    {% endblock %}

    <script>
        function toggleMenu () {
            var menuElement = document.getElementById('navbar');
            var menuIconElement = document.getElementById('menu_icon')

            if (menuElement.classList.contains('hidden')) {
                menuElement.classList.remove('hidden');
                menuElement.classList.add('absolute');
                menuElement.classList.add('block');

                menuIconElement.classList.remove('left-8');
                menuIconElement.classList.remove('top-5');
                menuIconElement.classList.add('left-60')
                menuIconElement.classList.add('top-12')
            } else {
                menuElement.classList.add('hidden');
                menuElement.classList.remove('block');
                menuElement.classList.remove('absolute');

                menuIconElement.classList.remove('left-60');
                menuIconElement.classList.remove('top-12');
                menuIconElement.classList.add('left-8')
                menuIconElement.classList.add('top-5')
            } 
        }

        function hideMenu () {
            var menuElement = document.getElementById('navbar');
            var menuIconElement = document.getElementById('menu_icon')

            if (menuElement.classList.contains('block')) {
                menuElement.classList.add('hidden');
                menuElement.classList.remove('block');
                menuElement.classList.remove('absolute');

                menuIconElement.classList.remove('left-60');
                menuIconElement.classList.remove('top-12');
                menuIconElement.classList.add('left-8')
                menuIconElement.classList.add('top-5')
            }
        }
    </script>

</body>
</html>

expensetracker/templates/expensetracker/dashboard.html
{% extends 'expensetracker/base.html' %}

{% load humanize %}


{% block head %}
<script src="https://code.highcharts.com/highcharts.js"></script>
{% endblock %}


{% block title %}Dashboard{% endblock %}


{% block content %}
<div id="dashboard" class="w-full flex flex-col lg:flex-row items-center">

    <div id="summary" class="w-full md:w-4/5 lg:w-3/5 rounded-xl flex flex-col gap-4">

        <div id="chart-container" class="w-full h-96 rounded-xl bg-teal-900"></div>

        <div id="overview" class="w-full h-max rounded-xl grid grid-cols-2 gap-4">
            <div id="income" class="p-4 rounded-xl bg-green-900 flex flex-col justify-even">
                <h1 class="text-3xl font-semibold">Total Income</h1>
                <P class="p-4 text-5xl text-center font-bold">+{{total_income|intcomma}}</P>
            </div>
    
            <div id="expense" class="p-4 rounded-xl bg-red-500 flex flex-col justify-even">
                <h1 class="text-3xl font-semibold">Total Expense</h1>
                <P class="p-4 text-5xl text-center font-bold">-{{total_expense|intcomma}}</P>
            </div>

            <div id="balance" class="col-span-2 p-4 rounded-xl {% if total_balance > 0 %} bg-green-900 {% else %} bg-red-500 {% endif %} flex flex-col justify-even">
                <h1 class="text-3xl font-semibold">Total Balance</h1>
                <P class="p-4 text-5xl text-center font-bold">{% if total_balance > 0 %} +{{total_balance|intcomma}} {% else %} {{total_balance|intcomma}} {% endif %}</P>
            </div>
        </div>

    </div>

    <div id="details" class="w-full md:w-4/5 lg:w-2/5 m-4 mx-auto rounded-xl flex flex-col gap-6">

        <div id="recent_history" class="p-4 rounded-xl text-emerald-600">
            <h1 class="text-center pb-5 text-3xl font-semibold">Recent History</h1>
            {% if recent_history %}
            <div class="rounded-xl flex flex-col gap-4">

                {% for transaction in recent_history %}
                <div class="flex justify-between px-3 py-2 rounded-xl bg-emerald-800 text-lg font-semibold {% if transaction.type == 'IN' %} text-green-700 {% else %} text-rose-700 {% endif %}">
                    <div class="w-1/3 my-auto text-center">{{transaction.name}}</div>
                    <div class="w-1/3 my-auto text-center">{{transaction.category}}</div>
                    <div class="w-1/3 my-auto text-center">{% if transaction.type == 'IN' %} +{{transaction.amount|intcomma}} {% else %} -{{transaction.amount|intcomma}} {% endif %}</div>
                </div>
                {% endfor %}

            </div>
            {% else %}

            <div>
                <p>Add a transaction to see recent transactions</p>
            </div>

            {% endif %}
        </div>

        <div id="income-category" class="p-4 rounded-xl text-black flex flex-col gap-4">

            <div class="flex justify-between items-center rounded-xl text-emerald-600">
                <div class="w-3/12 text-center inline-block font-semibold">Min</div>
                <div class="w-6/12 text-center text-2xl font-semibold inline-block font-semibold">Income Category</div>
                <div class="w-3/12 text-center inline-block font-semibold">Max</div>
            </div>
            <div class="py-2 flex justify-between items-center rounded-xl bg-emerald-800">
                <div class="w-3/12 text-center inline-block font-semibold">{{lowest_income_category}}</div>
                <div class="w-6/12 text-center text-2xl font-semibold inline-block font-semibold"></div>
                <div class="w-3/12 text-center inline-block font-semibold">{{highest_income_category}}</div>
            </div>

        </div>

        <div id="expense-category" class="p-4 rounded-xl text-black flex flex-col gap-4">

            <div class="flex justify-between items-center rounded-xl text-emerald-600">
                <div class="w-3/12 text-center inline-block font-semibold">Min</div>
                <div class="w-6/12 text-center text-2xl font-semibold inline-block font-semibold">Expense Category</div>
                <div class="w-3/12 text-center inline-block font-semibold">Max</div>
            </div>
            <div class="py-2 flex justify-between items-center rounded-xl bg-emerald-800">
                <div class="w-3/12 text-center inline-block font-semibold">{{lowest_expense_category}}</div>
                <div class="w-6/12 text-center text-2xl font-semibold inline-block font-semibold"></div>
                <div class="w-3/12 text-center inline-block font-semibold">{{highest_expense_category}}</div>
            </div>

        </div>

    </div>

</div>        
{% endblock %}


{% block scripts %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Fetch data from your Django backend
        fetch('/expensetracker/chart-data/')
            .then((response) => response.json())
            .then((data) => {
                
                Highcharts.chart('chart-container', {
                    chart: {
                        type: 'areaspline',
                        backgroundColor: null,
                        style: {
                            color: '#000000' // Set text color to black
                        }
                    },
                    title: {
                        text: data.label,
                        align: 'center',
                        style: {
                            color: '#000000' // Text color for title
                        }
                    },
                    legend: {
                        layout: 'horizontal',
                        align: 'left',
                        verticalAlign: 'top',
                        x: 120,
                        y: 35,
                        floating: true,
                        borderWidth: 0,
                        backgroundColor: null,
                        itemStyle: {
                            color: '#000000' 
                        }
                    },
                    xAxis: {
                        // categories: data.labels,
                        visible: false,
                        labels: {
                            style: {
                                color: '#000000' 
                            }
                        },
                        gridLineWidth: 0
                    },
                    yAxis: {
                        title: {
                            text: 'Amount',
                            style: {
                                color: '#000000'
                            }
                        },
                        labels: {
                            style: {
                                color: '#000000' 
                            }
                        },
                        gridLineWidth: 0
                    },
                    tooltip: {
                        shared: false,
                    },
                    credits: {
                        enabled: false
                    },
                    plotOptions: {
                        areaspline: {
                            fillOpacity: 0.5
                        }
                    },
                    series: [{
                        name: 'Income',
                        data: data.income_values,
                        color: 'rgb(21 128 61)'
                    }, {
                        name: 'Expense',
                        data: data.expense_values,
                        color: 'rgb(190 18 60)'
                    }]
                });
            });
    });
</script>
{% endblock %}