allprojects/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('bookmyhotel/', include('bookmyhotel.urls')),
    path('shopmart/', include('shopmart.urls')),
    path('expensetracker/', include('expensetracker.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

bookmyhotel/urls.py
from django.urls import path
from . import views

app_name = 'bookmyhotel'

urlpatterns = [
    path('', views.hotel_list, name='hotels'),

    path('admin/', views.admin, name='admin'),

    path('add-user/', views.add_user, name='add-user'),
    
    path('<str:hotel_id>/', views.hotel_detail, name='hotel-detail'),

    path('<str:hotel_id>/submit-rating/', views.submit_rating, name='submit-rating'),

    path('rooms/<str:hotel_room_id>/', views.hotel_room_detail, name='hotel-room-detail'),

    path('rooms/<str:hotel_room_id>/book-room/', views.book_room, name='book-room'),

    path('create-room/<str:room_id>/', views.create_room, name='create-room'),

    path('edit-user/<str:id>/', views.edit_user, name='edit-user'),

    path('room/<str:room_id>/', views.room, name='room'),

    path('delete-room/<str:room_id>/', views.delete_room, name='delete-room'),
]

core/urls.py
from django.urls import path, reverse_lazy
from . import views

from .forms import LoginForm, MyPasswordResetForm, MySetPasswordForm
from django.contrib.auth import views as authView

app_name = 'core'

urlpatterns = [
    path('', views.welcome_page, name='welcome_page'),

    path('signup/', views.signup, name='signup'),

    path('login/', authView.LoginView.as_view(
        template_name = 'core/login_form.html',
        authentication_form = LoginForm
    ), name='login'),

    path('logout/', authView.LogoutView.as_view(), name='logout'),

    path('password-reset/', authView.PasswordResetView.as_view(
        template_name='core/password_reset.html',
        email_template_name='core/password_reset_email.html',
        form_class=MyPasswordResetForm,
        success_url= reverse_lazy('core:password_reset_done')
    ), name='password_reset'),

    path('password-reset-done/', authView.PasswordResetDoneView.as_view(
        template_name='core/password_reset_done.html'
    ), name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', authView.PasswordResetConfirmView.as_view(
        template_name='core/password_reset_confirm.html',
        form_class=MySetPasswordForm,
        success_url = reverse_lazy('core:password_reset_complete')
    ), name='password_reset_confirm'),

    path('password-reset-complete/', authView.PasswordResetCompleteView.as_view(
        template_name='core/password_reset_complete.html'
    ), name='password_reset_complete'),
]

bookmyhotel/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator

from core.models import User

import uuid

# Create your models here.
class BaseModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    created_at = models.DateTimeField(default=timezone.now, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class LocationType(models.TextChoices):
    URBAN = 'UR', 'Urban'
    AIRPORT = 'AP', 'Airport'
    RESORT = 'RE', 'Resort'
    MOUNTAIN = 'MT', 'Mountain'
    BEACHFRONT = 'BF', 'Beachfront'
    BOUTIQUE = 'BO', 'Boutique'
    ECO = 'EC', 'Eco'
    HIGHWAY = 'HW', 'Highway'
    CASINO = 'CA', 'Casino'


class RoomType(models.TextChoices):
    STANDARD = 'ST', 'Standard'
    DELUXE = 'DX', 'Deluxe'
    SUITE = 'SU', 'Suit'
    FAMILY = 'FR', 'Family'


class Amenity(BaseModel):
    amenity_name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['created_at',]

    def __str__(self):
        return self.amenity_name
    

# Hotel related models    

class Hotel(BaseModel):
    hotel_name = models.CharField(max_length=255)
    location = models.CharField(max_length=255, blank=True, null=True)
    amenities = models.ManyToManyField(Amenity, blank=True)
    location_type = models.CharField(max_length=2, choices=LocationType.choices, default=LocationType.URBAN,)

    # latitude = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)
    # longitude = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)

    def get_lowest_room_price(self):
        return self.rooms.order_by('price').first().price if self.rooms.exists() else None
    
    def get_average_rating(self):
        ratings = self.ratings.all()

        if not ratings:
            return None
        
        total = sum(rating.average_rating() for rating in ratings)
        count = ratings.count()

        return round(total / count, 2)

    def __str__(self):
        return self.hotel_name
    
class HotelImage(BaseModel):
    hotel = models.ForeignKey(Hotel, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='bookmyhotel/hotel_images')

    def __str__(self):
        return f"Image for {self.hotel.hotel_name}"
    


# Hotel-room related models    

class HotelRoom(BaseModel):
    hotel = models.ForeignKey(Hotel, related_name='rooms', on_delete=models.CASCADE)
    room_number = models.IntegerField(unique=True)
    room_type = models.CharField(max_length=2, choices=RoomType.choices, default=RoomType.STANDARD)
    price = models.FloatField()
    description = models.TextField(blank=True, null=True)

    def is_booked(self, check_date):
        return self.bookings.filter(start_date__lte=check_date, end_date__gte=check_date).exists()
    
    def get_average_rating(self):
        ratings = self.ratings.all()

        if not ratings:
            return None
        
        total = sum(rating.average_rating() for rating in ratings)
        count = ratings.count()

        return round(total / count, 2)

    def __str__(self):
        return f'{self.room_number} at {self.hotel.hotel_name}'
    
class HotelRoomImage(BaseModel):
    hotel_room = models.ForeignKey(HotelRoom, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='bookmyhotel/hotel_room_images')

    def __str__(self):
        return f"Image for room {self.hotel_room.room_number} at {self.hotel_room.hotel.hotel_name}"
    

# Booking related models

class Booking(BaseModel):
    room = models.ForeignKey(HotelRoom, related_name='bookings', blank=True, null=True, on_delete=models.SET_NULL)
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return f'Booking for {self.room.room_number} at {self.room.hotel.hotel_name} from {self.start_date} to {self.end_date}'
    

# Rating related models

class Rating(models.Model):
    hotel = models.ForeignKey(Hotel, related_name='ratings', blank=True, null=True, on_delete=models.CASCADE)
    room = models.ForeignKey(HotelRoom, related_name='ratings', blank=True, null=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='ratings', blank=True, null=True, on_delete=models.SET_NULL)
    cleanliness = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    service = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    location = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    amenities = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    room_quality = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    comment = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def average_rating(self):
        total = self.cleanliness + self.service + self.location + self.amenities + self.room_quality
        return round(total / 5, 2)
    
    def __str__(self):
        return f'Rating {self.average_rating()} for hotel {self.hotel.hotel_name} by {self.user.name}'
    










class Message(models.Model):
    body = models.TextField()
    sent_by = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.sent_by.name}-{self.body}'
    
    class Meta:
        ordering = ('created_at',)


class Room(models.Model):
    WAITING = 'waiting'
    ACTIVE = 'active'
    CLOSED = 'closed'

    ROOM_STATUS = (
        (WAITING, 'Waiting'),
        (ACTIVE, 'Active'),
        (CLOSED, 'Closed'),
    )

    room_id = models.CharField(max_length=255)
    url = models.CharField(max_length=255, blank=True, null=True)
    messages = models.ManyToManyField(Message, blank=True)

    client = models.ForeignKey(User, related_name='client_rooms', blank=True, null=True, on_delete=models.SET_NULL)
    agent = models.ForeignKey(User, related_name='agent_rooms', blank=True, null=True, on_delete=models.SET_NULL)

    status = models.CharField(max_length=20, choices=ROOM_STATUS, default=WAITING)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.client.name}-{self.room_id}-{self.status}'
    
    class Meta:
        ordering = ('-created_at',)

core/models.py
from django.db import models

from django.contrib.auth.models import UserManager, AbstractBaseUser, PermissionsMixin
from django.utils import timezone

import uuid

# Create your models here.

class CustomUserManager(UserManager):
    def _create_user(self, email, name, password, **extra_fields):
        if not email:
            return ValueError('Please provide a valid email address!')
        
        email = self.normalize_email(email)
        user = self.model(email=email, name=name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email=None, name=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, name, password, **extra_fields)

    def create_superuser(self, email=None, name=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(email, name, password, **extra_fields)
    

class User(AbstractBaseUser, PermissionsMixin):
    CUSTOMER = 'customer'
    AGENT = 'agent'
    MANAGER = 'manager'

    ROLE_CHOICES = (
        (CUSTOMER, 'Customer'),
        (AGENT, 'Agent'),
        (MANAGER, 'Manager'),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=255, blank=True, default='')
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default=CUSTOMER)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['name',]

bookmyhotel/forms.py
from django import forms

from .models import Rating, Amenity, LocationType
from core.models import User

from django.core.exceptions import ValidationError
from datetime import date

BOOK_ROOM_INPUT_CLASSES = 'w-full mb-2 py-1 px-3 rounded-xl bg-gray-400 text-gray-800 border'
INPUT_CLASSES = 'w-full px-3 rounded-lg bg-gray-400 text-gray-800 border'


class BookRoomForm(forms.Form):
    start_date = forms.DateField(widget=forms.DateInput(attrs={
        'type': 'date',
        'placeholder': 'Enter your check-in date...',
        'class': BOOK_ROOM_INPUT_CLASSES
    }))

    end_date = forms.DateField(widget=forms.DateInput(attrs={
        'type': 'date',
        'placeholder': 'Enter your check-out date...',
        'class': BOOK_ROOM_INPUT_CLASSES
    }))

    def clean(self):
        cleaned_data = super().clean()
        check_in = cleaned_data.get('start_date')
        check_out = cleaned_data.get('end_date')

        if check_in and check_out:
            if check_in < date.today():
                raise ValidationError('The check-in date cannot be in the past.')
            
            if check_out <= check_in:
                raise ValidationError("Check-out date must be after check-in date.")
            
        return cleaned_data
    

class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ('cleanliness', 'service', 'location', 'amenities', 'room_quality', 'comment')
        widgets = {
            'cleanliness': forms.NumberInput(attrs={
                'class': INPUT_CLASSES,
                'placeholder': 'Rate between 1-5',
            }),

            'service': forms.NumberInput(attrs={
                'class': INPUT_CLASSES,
                'placeholder': 'Rate between 1-5',
            }),

            'location': forms.NumberInput(attrs={
                'class': INPUT_CLASSES,
                'placeholder': 'Rate between 1-5',
            }),

            'amenities': forms.NumberInput(attrs={
                'class': INPUT_CLASSES,
                'placeholder': 'Rate between 1-5',
            }),

            'room_quality': forms.NumberInput(attrs={
                'class': INPUT_CLASSES,
                'placeholder': 'Rate between 1-5',
            }),

            'comment': forms.Textarea(attrs={
                'class': 'w-full h-[150px] px-3 py-2 rounded-lg bg-gray-400 text-gray-800 border',
                'placeholder': 'Add a comment. Thank you...',
            }),
        }

    def clean(self):
        clean_data = super().clean()
        for field_name in ['cleanliness', 'service', 'location', 'amenities', 'room_quality']:
            rating = clean_data.get(field_name)
            if rating is not None and (rating < 1 or rating > 5):
                self.add_error(field_name, forms.ValidationError(f"{field_name.capitalize()} rating must be between 0 and 5."))


class HotelFilterForm(forms.Form):
    amenities = forms.ModelMultipleChoiceField(
        queryset=Amenity.objects.all(),
        widget = forms.CheckboxSelectMultiple(attrs={'onchange': 'this.form.submit();'}),
        required = False
    )

    location_types = forms.MultipleChoiceField(
        choices=LocationType.choices,
        widget=forms.CheckboxSelectMultiple(attrs={'onchange': 'this.form.submit();'}),
        required=False,
        label="Location Types"
    )













class AddUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'name', 'role', 'password',)
        widgets = {
            'email': forms.EmailInput(attrs={
                'placeholder': 'Email address...',
                'class': INPUT_CLASSES
            }),

            'name': forms.TextInput(attrs={
                'placeholder': 'Name...',
                'class': INPUT_CLASSES
            }),

            'role': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),

            'password': forms.PasswordInput(attrs={
                'placeholder': 'Enter a password...',
                'class': INPUT_CLASSES
            }),
        }


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'name', 'role',)
        widgets = {
            'email': forms.EmailInput(attrs={
                'placeholder': 'Email address...',
                'class': INPUT_CLASSES
            }),

            'name': forms.TextInput(attrs={
                'placeholder': 'Name...',
                'class': INPUT_CLASSES
            }),

            'role': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
        }

bookmyhotel/templates/bookmyhotel/admin.html
{% extends 'bookmyhotel/base.html' %}


{% block title %}{{title}}{% endblock %}


{% block content %}

    {% if perms.core.view_user %}
        <div class="mt-2">
            <h2 class="mb-4 text-center text-2xl font-semibold">Staffs</h2>

            <a href="{% url 'bookmyhotel:add-user' %}" class="inline-block py-2 px-4 bg-emerald-600 text-white rounded-xl shadow-2xl hover:bg-emerald-700 transition ease-in-out duration-300">Add Staff</a>

            <div class="mt-6 shadow-2xl">
                {% for user in users %}
                    <div class="inline-block flex justify-between gap-4 px-3 py-2 {% cycle 'bg-gray-800' '' %}">
                        <p class="w-1/4 px-2 text-center">
                            <a href="">{{ user.name }}</a>
                        </p>

                        <p class="w-1/4 px-2 text-center">{{ user.email }}</p>

                        <p class="w-1/4 px-2 text-center">{{ user.get_role_display }}</p>

                        <p class="w-1/4 px-2 text-center">
                            {% if perms.core.change_user %}
                                <a href="{% url 'bookmyhotel:edit-user' user.id %}" class="underline">Edit</a>
                            {% endif %}
                        </p>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}

    <hr class="my-6">

    <div class="mt-8">
        <h2 class="mb-8 text-center text-2xl font-semibold">Rooms</h2>

        <div class="grid grid-cols-3 gap-4">
            {% for room in rooms %}
                <div class="p-4 rounded-xl shadow-2xl {% if room.status == 'waiting' %} bg-emerald-800 {% elif room.status == 'active' %} bg-yellow-800 {% else %} bg-gray-800 {% endif %}">
                    <h3 class="mb-4 text-center text-lg">Chat</h3>

                    <div class="flex flex-col items-center">
                        <div>
                            <p>
                                <b>ID: </b>{{ room.room_id }}<br>
                                <b>Name: </b>{{ room.client.name }}<br>
                                <b>Status: </b>{{ room.get_status_display }}<br>
                                <b>Agent: </b>{% firstof room.agent.name 'None yet...' %}
                            </p>
                        </div>

                        <div class="flex justify-between items-center gap-4">
                            <a href="{% url 'bookmyhotel:room' room.room_id %}" class="mt-4 inline-block py-2 px-6 bg-emerald-600 text-white rounded-xl shadow-2xl hover:bg-emerald-700 transition ease-in-out duration-300">Join</a>
                            <a href="{% url 'bookmyhotel:delete-room' room.room_id %}" class="mt-4 inline-block py-2 px-6 bg-rose-700 text-white rounded-xl shadow-2xl hover:bg-rose-800 transition ease-in-out duration-300">Delete</a>
                        </div>
                    </div>

                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

bookmyhotel/templates/bookmyhotel/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}  {% endblock %} | BookMyHotel</title>
        <link href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css" rel="stylesheet">

        <script src="https://cdn.tailwindcss.com"></script>
        {% block style %}
        {% endblock %}
    </head>

    <body class="w-screen text-white bg-gradient-to-bl from-slate-800 to-gray-600">

        <div class="p-2">

            <nav class="w-4/5 mx-auto mt-2 px-3 py-3 flex justify-between items-center rounded-full shadow-2xl bg-gradient-to-bl from-gray-700 to-slate-800">
                
                <div class="flex justify-start items-center">
                    <img src="/media/bookmyhotel/logo.png" alt="logo" class="w-10 h-10">
                    <a href="{% url 'bookmyhotel:hotels' %}"  class="text-xl text-slate-400 font-semibold">BookMyHotel</a>
                </div>    

                <div class="flex items-center space-x-4">
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'core:logout' %}" class="inline-block w-20 text-center text-sm px-3 py-2 bg-gray-600 rounded-full shadow-2xl hover:bg-gray-800 transition ease-in-out duration-300">Logout</a>
                    {% else %}
                        <a href="{% url 'core:signup' %}" class="inline-block w-20 text-center text-sm px-3 py-2 bg-gray-600 rounded-full shadow-2xl hover:bg-gray-800 transition ease-in-out duration-300">Signup</a>
                        <a href="{% url 'core:login' %}" class="inline-block w-20 text-center text-sm px-3 py-2 bg-gray-600 rounded-full shadow-2xl hover:bg-gray-800 transition ease-in-out duration-300">Login</a>
                    {% endif %}

                    {% if request.user.is_staff %}
                        <a href="{% url 'bookmyhotel:admin' %}" class="inline-block px-3 py-2 text-sm bg-gray-600 rounded-full shadow-2xl hover:bg-gray-800 transition ease-in-out duration-300">Admin</a>
                    {% endif %}
                </div>
            </nav>

            {% if messages %}
                <div class="message w-max mx-auto mt-4 px-10 py-2 text-center bg-slate-800 rounded-full shadow-2xl">
                    {% for message in messages %}
                        <p>{{ message }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            
        </div>

        <main class="max-w-6xl mx-auto p-6">
            {% block content %}

            {% endblock %}

            {% if not request.user.is_staff %}
                {% include 'bookmyhotel/support/partials/bubble_chat.html' %}
            {% endif %}
        </main>

        <footer class="w-full py-6 px-6 bottom-0 bg-gray-600 text-white text-center text-xs">
            <p>Copyright (c) 2023 - Book My Hotel</p>
        </footer>

        {% if request.user.is_authenticated %}

            {{request.user.name|json_script:'user_name'}}
            {{request.user.id|json_script:'user_id'}}

        {% endif %}


        {% block scripts %}

        {% endblock %}


        {% if not request.user.is_staff %}
            <script src="{% static 'bookmyhotel/js/main.js' %}"></script>
        {% endif %}
        
    </body>

</html>

bookmyhotel/templates/bookmyhotel/hotel_list.html
{% extends "bookmyhotel/base.html" %}

{% load static hotelextras %}


{% block title %}{{ title }}{% endblock %}


{% block style %}
<style>
    .checkbox-button input[type='checkbox'] {
        display: none;
    }
    
    .checkbox-button label {
        display: inline-block;
        width: 100%;
        margin: 5px;
        background-color: rgb(75 85 99);
        color: #ffffff;
        padding: 5px 10px;
        border-radius: 15px;
        cursor: pointer;
        transition: background-color 0.2s, color 0.2s;
    }

    .checkbox-button label.location_types:hover {
        background-color: rgb(31 41 55);
    }

    .checkbox-button label.amenities:hover {
        background-color: rgb(17 24 39);
    }
    
    
    .checkbox-button input[type='checkbox']:checked + label.location_types {
        background-color: rgb(31 41 55);
    }

    .checkbox-button input[type='checkbox']:checked + label.amenities {
        background-color: rgb(17 24 39);
    }
</style>
    
{% endblock %}


{% block content %}
<h2 class="mb-8 text-center text-2xl font-semibold">Hotels</h2>

<!-- {{ hotel_filter_form.location_types }} -->
<form id="location_types_filter" action="." method="get" class="mb-4">
    <div class="checkbox-button flex flex-wrap gap-3 justify-center mx-auto px-5 overflow-x-auto rounded-xl">
        {% for choice in hotel_filter_form.location_types %}
            <div>
                {{ choice.tag }}
                <label for="id_location_types_{{forloop.counter0}}" class="text-center location_types">{{ choice.choice_label }}</label>
            </div>
        {% endfor %}
    </div>
</form>

<div class="w-max mx-auto p-4 md:hidden">
    <button id="filterToggle" class="py-2 px-10 bg-gray-600 text-white rounded-lg hover:bg-gray-800 transition ease-in-out duration-300" onclick="toggleFilter()">Filters</button>
</div>

<div class="flex flex-col md:flex-row h-screen gap-4">

    <div id="filter" class="hidden md:block md:w-1/4 p-4 bg-slate-800 md:flex flex-col justify-start items-center rounded-xl shadow-2xl transition-transform duration-300 ease-in-out">
        <!-- Filter Content Goes Here -->
        <h1 class="text-center text-xl mt-4 mb-6">Filter</h1>

        <form id="amenities_filter" method="get" action="." class="mb-4">
            <input name="query" value="{{query}}" type="text" class="w-full mb-8 py-1 px-4 bg-slate-700 border border-2 border-gray-950 rounded-xl" placeholder="Search your hotel">

            <!-- {{ hotel_filter_form.amenities }} -->
            <h1 class="mb-4 text-lg font-semibold">Amenities:</h1>

            <div class="checkbox-button flex flex-row flex-wrap md:flex-col items-center gap-2 rounded-lg">
                {% for amenity in hotel_filter_form.amenities %}
                    <div class="md:w-4/5">
                        {{ amenity.tag }}
                        <label for="id_amenities_{{forloop.counter0}}" class="text-center amenities">{{ amenity.choice_label }}</label>
                    </div>
                {% endfor %}
            </div>
        </form>

        <hr class="w-full mb-4">

        <a href="{% url 'bookmyhotel:hotels' %}" class="mb-4 py-1 px-3 bg-emerald-600 rounded-lg hover:bg-emerald-700 transition ease-in-out duration-300">Clear Filter</a>
    </div>

    <div id="hotel_list" class="w-full md:w-3/4 mx-auto flex flex-col gap-4 overflow-y-auto rounded-xl">
        {% for hotel in hotels %}
            <div id="hotel_{{ forloop.counter0 }}" class="p-4 rounded-xl bg-slate-800 flex flex-col md:flex-row justify-center items-center gap-4 shadow-lg">
                
                {% with hotel.images.all as images %}
                {% if images %}
                <div id="hotel_{{ forloop.counter0 }}_image" class="w-full h-80 md:w-1/2 md:h-full lg:w-2/5 bg-white rounded-lg overflow-hidden">
                    <img src="{{ images.0.image.url }}" alt="{{hotel.hotel_name}}" class="w-full h-full object-cover">
                </div>
                {% else %}
                <div id="hotel_{{ forloop.counter0 }}_image" class="w-2/5 h-60 bg-gray-800 rounded-lg flex items-center justify-center">
                    <span class="text-gray-500">No image available</span>
                </div>
                {% endif %}
                {% endwith %}

                <div id="hotel_{{ forloop.counter0 }}_detail" class="w-full h-max md:w-1/2 lg:w-3/5 p-2 flex flex-col justify-start bg-slate-700 rounded-xl">

                    <div class="w-full p-4 text-2xl font-semibold">{{ hotel.hotel_name }}</div>
                
                    <p class="w-full py-2 px-5 text-lg">Deals starting from ${{ hotel.get_lowest_room_price }}</p>

                    <p class="w-full py-2 px-5 text-lg">Location : {{ hotel.location }}</p>

                    <p class="w-full py-2 px-5 text-lg">Rating : {{ hotel.get_average_rating|stars|safe }}</p>

                    <div class="w-full py-2 px-5 flex justify-center items-center">
                        <a href="{% url 'bookmyhotel:hotel-detail' hotel.id %}" class="mt-2 inline-block py-2 px-6 bg-emerald-600 text-white rounded-xl hover:bg-emerald-700 transition ease-in-out duration-300">View Deals</a>
                    </div>

                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}


{% block scripts %}
<script>
    function toggleFilter() {
        var filterElement = document.getElementById('filter');
        if (filterElement.classList.contains('hidden')) {
        filterElement.classList.remove('hidden');
        filterElement.classList.add('flex');
        } else {
        filterElement.classList.add('hidden');
        filterElement.classList.remove('flex');
        }
    }
</script>
{% endblock %}