allprojects/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('bookmyhotel/', include('bookmyhotel.urls')),
    path('shopmart/', include('shopmart.urls')),
    path('expensetracker/', include('expensetracker.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

bookmyhotel/urls.py
from django.urls import path
from . import views

app_name = 'bookmyhotel'

urlpatterns = [
    path('', views.hotel_list, name='hotels'),

    path('admin/', views.admin, name='admin'),

    path('add-user/', views.add_user, name='add-user'),
    
    path('<str:hotel_id>/', views.hotel_detail, name='hotel-detail'),

    path('<str:hotel_id>/submit-rating/', views.submit_rating, name='submit-rating'),

    path('rooms/<str:hotel_room_id>/', views.hotel_room_detail, name='hotel-room-detail'),

    path('rooms/<str:hotel_room_id>/book-room/', views.book_room, name='book-room'),

    path('create-room/<str:room_id>/', views.create_room, name='create-room'),

    path('edit-user/<str:id>/', views.edit_user, name='edit-user'),

    path('room/<str:room_id>/', views.room, name='room'),

    path('delete-room/<str:room_id>/', views.delete_room, name='delete-room'),
]

core/urls.py
from django.urls import path, reverse_lazy
from . import views

from .forms import LoginForm, MyPasswordResetForm, MySetPasswordForm
from django.contrib.auth import views as authView

app_name = 'core'

urlpatterns = [
    path('', views.welcome_page, name='welcome_page'),

    path('signup/', views.signup, name='signup'),

    path('login/', authView.LoginView.as_view(
        template_name = 'core/login_form.html',
        authentication_form = LoginForm
    ), name='login'),

    path('logout/', authView.LogoutView.as_view(), name='logout'),

    path('password-reset/', authView.PasswordResetView.as_view(
        template_name='core/password_reset.html',
        email_template_name='core/password_reset_email.html',
        form_class=MyPasswordResetForm,
        success_url= reverse_lazy('core:password_reset_done')
    ), name='password_reset'),

    path('password-reset-done/', authView.PasswordResetDoneView.as_view(
        template_name='core/password_reset_done.html'
    ), name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', authView.PasswordResetConfirmView.as_view(
        template_name='core/password_reset_confirm.html',
        form_class=MySetPasswordForm,
        success_url = reverse_lazy('core:password_reset_complete')
    ), name='password_reset_confirm'),

    path('password-reset-complete/', authView.PasswordResetCompleteView.as_view(
        template_name='core/password_reset_complete.html'
    ), name='password_reset_complete'),
]

expensetracker/urls.py
from django.urls import path

from expensetracker import views


app_name = 'expensetracker'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('new/', views.new, name='new'),
    path('analytics/', views.analytics, name='analytics'),
    path('list/', views.list, name='list'),
    path('incomes/', views.incomes, name='incomes'),
    path('expenses/', views.expenses, name='expenses'),
    path('analytics-data/', views.analytics_data, name='analytics_data'),
    path('chart-data/', views.chart_data, name='chart_data'),
]

shopmart/urls.py
from django.urls import path
from . import views

app_name = 'shopmart'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('browse/', views.get_products, name='browse'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('policy/', views.policy, name='policy'),
    path('terms/', views.terms, name='terms'),
    path('new/', views.new_product, name='new'),
    path('inbox/', views.inbox, name='inbox'),
    path('config/', views.stripe_config, name='config'),
    path('payment/success/', views.SuccessView.as_view(), name='success'),
    path('payment/cancelled/', views.CancelledView.as_view(), name='cancelled'),
    path('payment/webhook/', views.stripe_webhook, name='webhook'),
    path('<str:product_pk>/', views.product_detail, name='detail'),
    path('<str:product_pk>/edit/', views.edit_product, name='edit'),
    path('<str:product_pk>/delete/', views.product_delete, name='delete'),
    path('new/<str:product_pk>/', views.new_chatroom, name='new-chatroom'),
    path('inbox/<str:chatroom_pk>/', views.chatroom, name='chatroom'),
    path('create-checkout-session/<str:product_pk>/', views.create_checkout_session, name='checkout'),
]

core/models.py
from django.db import models

from django.contrib.auth.models import UserManager, AbstractBaseUser, PermissionsMixin
from django.utils import timezone

import uuid

# Create your models here.

class CustomUserManager(UserManager):
    def _create_user(self, email, name, password, **extra_fields):
        if not email:
            return ValueError('Please provide a valid email address!')
        
        email = self.normalize_email(email)
        user = self.model(email=email, name=name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email=None, name=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, name, password, **extra_fields)

    def create_superuser(self, email=None, name=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(email, name, password, **extra_fields)
    

class User(AbstractBaseUser, PermissionsMixin):
    CUSTOMER = 'customer'
    AGENT = 'agent'
    MANAGER = 'manager'

    ROLE_CHOICES = (
        (CUSTOMER, 'Customer'),
        (AGENT, 'Agent'),
        (MANAGER, 'Manager'),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=255, blank=True, default='')
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default=CUSTOMER)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['name',]

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm, SetPasswordForm

from .models import User


INPUT_CLASSES = 'w-full mb-4 py-4 px-6 rounded-xl text-gray-800 border'

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email','name')
        widgets = {
            'email': forms.EmailInput(attrs={
                'placeholder': 'Your email-address...',
                'class': INPUT_CLASSES,
            }),

            'name': forms.TextInput(attrs={
                'placeholder': 'Your name...',
                'class': INPUT_CLASSES,
            }),
        }

    password1 = forms.CharField(label='Create a password:', widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password...',
        'class': INPUT_CLASSES
    }))

    password2 = forms.CharField(label='Repeat password:', widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat your password...',
        'class': INPUT_CLASSES
    }))

class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Enter your email address: ', widget=forms.EmailInput(attrs={
        'placeholder': 'example@example.com',
        'class': INPUT_CLASSES
    }))

    password = forms.CharField(label='Enter your password: ', widget=forms.PasswordInput(attrs={
        'placeholder': 'Password...',
        'class': INPUT_CLASSES
    }))


class MyPasswordResetForm(PasswordResetForm):
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': INPUT_CLASSES
    }))

class MySetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label='New password', widget=forms.PasswordInput(attrs={
        'placeholder': 'New password',
        'class': INPUT_CLASSES
    }))

    new_password2 = forms.CharField(label='Repeat new password', widget=forms.PasswordInput(attrs={
        'placeholder': 'New password confirmation',
        'class': INPUT_CLASSES
    }))

core/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from .forms import SignupForm

# Create your views here.
def welcome_page(request):
    return render(request, 'core/home.html', {
        'title': 'Welcome Page',
    })

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.save()

            messages.success(request, 'A user is added. Please login with provided credentials.')

            return redirect('/')
        
    else:
        form = SignupForm()
    
    return render(request, 'core/signup_form.html', {
        'form': form,
        'title': 'Signup'
    })

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}  {% endblock %} | BookMyHotel</title>
        <link href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css" rel="stylesheet">

        <script src="https://cdn.tailwindcss.com"></script>
        {% block style %}
        {% endblock %}
    </head>

    <body class="w-screen text-white bg-gradient-to-bl from-slate-800 to-gray-600">

        <div class="p-2">

            <nav class="w-4/5 mx-auto mt-2 px-3 py-3 flex justify-between items-center rounded-full shadow-2xl bg-gradient-to-bl from-gray-700 to-slate-800">
                
                <div class="flex justify-start items-center">
                    <img src="/media/logo.png" alt="logo" class="w-10 h-10">
                    <a href="{% url 'core:welcome_page' %}"  class="text-xl text-slate-400 font-semibold pl-5">Projects</a>
                </div>    

                <div class="flex items-center space-x-4">
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'core:logout' %}" class="inline-block w-20 text-center text-sm px-3 py-2 bg-gray-600 rounded-full shadow-2xl hover:bg-gray-800 transition ease-in-out duration-300">Logout</a>
                    {% else %}
                        <a href="{% url 'core:signup' %}" class="inline-block w-20 text-center text-sm px-3 py-2 bg-gray-600 rounded-full shadow-2xl hover:bg-gray-800 transition ease-in-out duration-300">Signup</a>
                        <a href="{% url 'core:login' %}" class="inline-block w-20 text-center text-sm px-3 py-2 bg-gray-600 rounded-full shadow-2xl hover:bg-gray-800 transition ease-in-out duration-300">Login</a>
                    {% endif %}
                </div>
            </nav>

            {% if messages %}
                <div class="message w-max mx-auto mt-4 px-10 py-2 text-center bg-slate-800 rounded-full shadow-2xl">
                    {% for message in messages %}
                        <p>{{ message }}</p>
                    {% endfor %}
                </div>
            {% endif %}
            
        </div>

        <main class="max-w-6xl mx-auto p-6">
            {% block content %}

            {% endblock %}
        </main>

        <footer class="w-full py-6 px-6 bottom-0 bg-gray-600 text-white text-center text-xs">
            <p>Copyright (c) 2024 - allprojects@codeblack04</p>
        </footer>


        {% block scripts %}

        {% endblock %}
        
    </body>

</html>

core/templates/core/home.html
{% extends 'core/base.html' %}


{% block title %} {{title}} {% endblock %}


{% block content %} 
<div id='projects' class='flex flex-col items-center justify-center pb-20'>
    <h1 class='text-[40px] font-semibold text-center text-transparent bg-clip-text bg-gradient-to-r from-purple-500 to-cyan-500 py-20'>My Projects</h1>

    <div class=''>

        <div class="flex flex-col md:flex-row gap-10 px-10">
            <a href="{% url 'shopmart:index' %}" class="transition hover:scale-110 flex-1">
                <div class='relative overflow-hidden rounded-lg shadow-lg border border-[#2A0E61] h-96'>
                    <Image
                    src='/media/projectthumbnail/shopmart1.png'
                    alt='BookMyHotel - Hotel Management Website'
                    class='w-full h-1/2 object-cover'
                    />
            
                    <div class='relative p-4 h-1/2 flex flex-col justify-between'>
                        <h1 class='text-2xl font-semibold text-white'>ShopMart - E-commerce Website</h1>
                        <p class='mt-2 text-gray-200'>A website for online shopping that features real-time chat, a payment option (Stripe), and advanced filtering options.</p>
                    </div>
                </div>
            </a>
    
            <a href="{% url 'bookmyhotel:hotels' %}" class="transition hover:scale-110 flex-1">
                <div class='relative overflow-hidden rounded-lg shadow-lg border border-[#2A0E61] h-96'>
                    <Image
                    src='/media/projectthumbnail/bookmyhotel1.png'
                    alt='BookMyHotel - Hotel Management Website'
                    class='w-full h-1/2 object-cover'
                    />
            
                    <div class='relative p-4 h-1/2 flex flex-col justify-between'>
                        <h1 class='text-2xl font-semibold text-white'>BookMyHotel - Hotel Management Website</h1>
                        <p class='mt-2 text-gray-200'>A website for hotel administration that includes live booking updates, chat help, staff management, and a rating system.</p>
                    </div>
                </div>
            </a>
            
            <a href="{% url 'expensetracker:dashboard' %}" class="transition hover:scale-110 flex-1">
                <div class='relative overflow-hidden rounded-lg shadow-lg border border-[#2A0E61] h-96'>
                    <Image
                    src='/media/projectthumbnail/expensetracker1.png'
                    alt='ExpenseTracker App'
                    class='w-full h-1/2 object-cover'
                    />
            
                    <div class='relative p-4 h-1/2 flex flex-col justify-between'>
                        <h1 class='text-2xl font-semibold text-white'>ExpenseTracker App</h1>
                        <p class='mt-2 text-gray-200'>A system for tracking expenses that provides analysis and keeps record of all transactions.</p>
                    </div>
                </div>
            </a>
        </div>
    
    </div>
    
</div>
{% endblock %}

core/templates/core/login_form.html
{% extends 'core/base.html' %}


{% block title %} Login {% endblock %}


{% block content %}
<div class="w-1/2 my-auto mx-auto p-6 bg-slate-800 rounded-xl">
    <h1 class="mb-6 text-center text-3xl">Login</h1>

    <form action="." method="post">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-3">Enter your email address:</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-3">Create a password:</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-300 text-gray-800 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>  
        {% endif %}  

        <div class="mb-3">
            <button class="w-20 text-center px-3 py-2 bg-gray-600 rounded-xl hover:bg-gray-700 transition ease-in-out duration-300">Login</button>
        </div>

        <p>Forgot password? <a href="{% url 'core:password_reset' %} " class="text-blue-700 hover:text-blue-900">Reset password</a></p>

    </form>
{% endblock %}

core/templates/core/password_reset.html
{%extends 'core/base.html'%}

{% block title %} Password Reset {% endblock %}

{%block content%}
<div class="w-1/2 my-6 mx-auto p-6 bg-slate-800 rounded-xl">
    <h1 class="mb-6 text-center text-3xl">Reset Password</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {% for field in form %}
        <div class="mb-3">
            <label class="inline-block mb-2">{{ field.label_tag }}</label><br>
            {{ field }}
            {% if field.errors %}
	        	<small>{{ field.errors|striptags  }}</small> 
	        {% endif %}
        </div>
        {% endfor %}
        <input type="submit" value="Send" class="mt-4 mr-4 px-6 py-3 text-sm font-semibold bg-slate-600 rounded-xl hover:bg-slate-700">
        <a href="{% url 'core:login' %}"  class="px-6 py-3 text-sm font-semibold bg-slate-600 rounded-xl hover:bg-slate-700 transition ease-in-out duration-300">Cancel</a>
    </form>
</div>
{%endblock content%}

core/templates/core/password_reset_complete.html
{%extends 'core/base.html'%}

{% block title %} Reset Complete {% endblock %}

{%block content%}
<div class="w-1/2 my-6 mx-auto p-6 bg-slate-800 rounded-xl">
    <h1 class="mb-6 text-3xl">Password Reset Complete</h1>
    <p>Your password has been reset, you can <a href="{% url 'core:login' %}" class="text-blue-700 hover:text-blue-900">login to your account now</a></p>

</div>
{%endblock content%}

core/templates/core/password_reset_confirm.html
{%extends 'core/base.html'%}

{% block title %} New Password {% endblock %}

{%block content%}

<div class="w-1/2 my-6 mx-auto p-6 bg-slate-800 rounded-xl">
	<h2 class="mb-6 text-3xl">Password Reset Confirm</h2>

	<form method="post" action=".">
	    {% csrf_token %}
	
	    {% for field in form %}
			<div class="mb-3">
	    		<label class="inline-block mb-2">{{ field.label_tag }}</label><br>
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags  }}</small> 
	        	{% endif %}
			</div>
		{% endfor %}
	  
	  <div class="mt-5 flex">
	    <button type="submit" class="px-6 py-3 text-sm font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700 transition ease-in-out duration-300">Reset Password</button>
	  </div>
	</form>
</div>

{%endblock content%}

core/templates/core/password_reset_done.html
{%extends 'core/base.html'%}

{% block title %} Check Email {% endblock %}

{%block content%}
<div class="w-1/2 my-6 mx-auto p-6 bg-slate-800 rounded-xl">
    <h1 class="mb-6 text-3xl">Password Reset</h1>
    <p>Please check your email and follow the instruction to reset your password.</p>

</div>
{%endblock content%}

core/templates/core/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'myauth:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your email, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

core/templates/core/signup_form.html
{% extends 'core/base.html' %}


{% block title %} {{title}} {% endblock %}


{% block content %}
<div class="w-1/2 my-auto mx-auto p-4 bg-slate-800 rounded-xl">
    <h1 class="mb-4 text-center text-3xl">{{ title }}</h1>

    <form action="." method="post">
        {% csrf_token %}

        <div class="mb-2">
            <label class="inline-block mb-3">Enter your email address:</label><br>
            {{ form.email }}
        </div>

        <div class="mb-2">
            <label class="inline-block mb-3">Enter your name:</label><br>
            {{ form.name }}
        </div>

        <div class="mb-2">
            <label class="inline-block mb-3">Create a password:</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-2">
            <label class="inline-block mb-3">Repeat :</label><br>
            {{ form.password2 }}
        </div>

        <!-- {{ form.as_p }} -->

        {% if form.errors or form.non_field_errors %}
            <div class="mb-2 p-6 bg-red-300 text-gray-800 rounded-xl">  
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>  
        {% endif %}  

        <div class="flex justify-center items-center">
            <button class="w-20 text-center px-3 py-2 bg-gray-600 rounded-xl hover:bg-gray-700 transition ease-in-out duration-300">Signup</button>
        </div>

    </form>
{% endblock %}