allprojects/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('bookmyhotel/', include('bookmyhotel.urls')),
    path('shopmart/', include('shopmart.urls')),
    path('expensetracker/', include('expensetracker.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, reverse_lazy
from . import views

from .forms import LoginForm, MyPasswordResetForm, MySetPasswordForm
from django.contrib.auth import views as authView

app_name = 'core'

urlpatterns = [
    path('', views.welcome_page, name='welcome_page'),

    path('signup/', views.signup, name='signup'),

    path('login/', authView.LoginView.as_view(
        template_name = 'core/login_form.html',
        authentication_form = LoginForm
    ), name='login'),

    path('logout/', authView.LogoutView.as_view(), name='logout'),

    path('password-reset/', authView.PasswordResetView.as_view(
        template_name='core/password_reset.html',
        email_template_name='core/password_reset_email.html',
        form_class=MyPasswordResetForm,
        success_url= reverse_lazy('core:password_reset_done')
    ), name='password_reset'),

    path('password-reset-done/', authView.PasswordResetDoneView.as_view(
        template_name='core/password_reset_done.html'
    ), name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', authView.PasswordResetConfirmView.as_view(
        template_name='core/password_reset_confirm.html',
        form_class=MySetPasswordForm,
        success_url = reverse_lazy('core:password_reset_complete')
    ), name='password_reset_confirm'),

    path('password-reset-complete/', authView.PasswordResetCompleteView.as_view(
        template_name='core/password_reset_complete.html'
    ), name='password_reset_complete'),
]

shopmart/urls.py
from django.urls import path
from . import views

app_name = 'shopmart'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('browse/', views.get_products, name='browse'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('policy/', views.policy, name='policy'),
    path('terms/', views.terms, name='terms'),
    path('new/', views.new_product, name='new'),
    path('inbox/', views.inbox, name='inbox'),
    path('config/', views.stripe_config, name='config'),
    path('payment/success/', views.SuccessView.as_view(), name='success'),
    path('payment/cancelled/', views.CancelledView.as_view(), name='cancelled'),
    path('payment/webhook/', views.stripe_webhook, name='webhook'),
    path('<str:product_pk>/', views.product_detail, name='detail'),
    path('<str:product_pk>/edit/', views.edit_product, name='edit'),
    path('<str:product_pk>/delete/', views.product_delete, name='delete'),
    path('new/<str:product_pk>/', views.new_chatroom, name='new-chatroom'),
    path('inbox/<str:chatroom_pk>/', views.chatroom, name='chatroom'),
    path('create-checkout-session/<str:product_pk>/', views.create_checkout_session, name='checkout'),
]

shopmart/forms.py
from django import forms
from .models import Product, ConversationMessage, Contact, Category

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl bg-cyan-900'

# core forms

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('full_name', 'email', 'subject', 'message')
        widgets = {
            'full_name': forms.TextInput(attrs={
                'placeholder': 'Full Name*',
                'class': INPUT_CLASSES
            }),

            'email': forms.TextInput(attrs={
                'placeholder': 'Email Address*',
                'class': INPUT_CLASSES
            }),

            'subject': forms.TextInput(attrs={
                'placeholder': 'Subject*',
                'class': INPUT_CLASSES
            }),

            'message': forms.Textarea(attrs={
                'placeholder': 'Send a message...',
                'class': INPUT_CLASSES
            }),
        }










# product forms



class NewProductForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = ('category', 'name', 'description', 'price', 'image',)
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }

class EditProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'price', 'image')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }








# chat forms





class NewMessageForm(forms.ModelForm):
    class Meta:
        model = ConversationMessage
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={
                'placeholder': 'Send a message...',
                'class': 'w-full py-4 px-6 rounded-xl border bg-cyan-950'
            })
        }




#browse forms




class CategoryForm(forms.Form):
    categories = forms.ModelMultipleChoiceField(
        queryset = Category.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'onChange': 'this.form.submit()'}),
        required= False,
    )

shopmart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from .models import Product, ChatRoom, Category
from .forms import NewProductForm, EditProductForm, NewMessageForm, ContactForm, CategoryForm

from django.db.models import Q, Min, Max

from django.views.generic.base import TemplateView

from django.conf import settings
from django.http.response import JsonResponse, HttpResponse

from django.core.paginator import Paginator

from django.db.models import Max

import stripe

# Create your views here.
# Core views

def index(request):
    if request.user.is_authenticated:
        products_list = Product.objects.filter(is_sold=False).exclude(created_by=request.user).order_by('-created_at')
    else:
        products_list = Product.objects.filter(is_sold=False).order_by('-created_at')

    categories = Category.objects.all()

    paginator = Paginator(products_list, 5)

    page_number = request.GET.get('page', 1)
    products = paginator.get_page(page_number)

    return render(request=request, template_name='shopmart/index.html', context={
        'title': 'Welcome',
        'products': products,
        'categories': categories,
    })

@login_required
def dashboard(request):
    products = Product.objects.filter(created_by = request.user)
    
    return render(request=request, template_name='shopmart/dashboard.html', context={
        'products': products,
        'title': 'Dashboard'
    })

def about(request):
    return render(request=request, template_name='shopmart/about.html', context={
        'title': 'About'
    })

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/shopmart/')
        
    else:
        form = ContactForm()
        
    return render(request=request, template_name='shopmart/contact.html', context={
        'form': form,
        'title': 'Contact'
    })

def policy(request):
    return render(request=request, template_name='shopmart/policy.html', context={
        'title': 'Policy'
    })

def terms(request):
    return render(request=request, template_name='shopmart/terms.html', context={
        'title': 'Terms'
    })









# Product views



def product_detail(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)
    related_products = Product.objects.filter(is_sold=False).filter(is_reserved=False).filter(category=product.category).exclude(pk=product_pk)

    if not product.is_sold:
        if product.is_reserved:
            if product.is_reservation_expired():
                print('Product in unreserved')
                product.unreserve()
                product.save()

    return render(request=request, template_name='shopmart/detail.html', context={
        'product': product,
        'related_products': related_products
    })

@login_required
def new_product(request):
    if request.method == 'POST':
        form = NewProductForm(request.POST, request.FILES)

        if form.is_valid():
            product_new = form.save(commit=False)
            product_new.created_by = request.user
            product_new.save()

            return redirect('shopmart:detail', product_new.id)
    
    else:
        form = NewProductForm()

    return render(request=request, template_name='shopmart/product_form.html', context={
        'form': form,
        'title': 'List New Product'
    })

@login_required
def edit_product(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)

    if request.method == 'POST':
        form = EditProductForm(request.POST, request.FILES, instance=product)
        
        if form.is_valid():
            form.save()
            return redirect('shopmart:detail', product.id)
        
    else:
        form = EditProductForm(instance=product)

    return render(request=request, template_name='shopmart/product_form.html', context={
        'form': form,
        'title': 'Edit Your product'
    })
        
@login_required
def product_delete(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)
    product.delete()
    return redirect('shopmart:dashboard')







# Chat views



@csrf_exempt
@login_required
def new_chatroom(request, product_pk):
    product = get_object_or_404(Product, id=product_pk)

    chatroom = ChatRoom.objects.filter(product=product).filter(members__in=[request.user.id])

    if chatroom:
        return redirect('shopmart:chatroom', chatroom_pk = chatroom.first().id)

    if request.method == 'POST':
        form = NewMessageForm(request.POST)

        if form.is_valid():
            message = form.save(commit=False)
            message.sent_by = request.user
            message.save()

            chatroom = ChatRoom.objects.create(product=product)
            chatroom.members.add(request.user)
            chatroom.members.add(product.created_by)
            chatroom.messages.add(message)
            chatroom.save()

            return redirect('shopmart:chatroom', chatroom_pk=chatroom.id)
    
    else:
        form = NewMessageForm()

    return render(request, 'shopmart/new_chatroom.html', {
        'form': form,
        'title': 'New Chatroom',
    })


@login_required
def chatroom(request, chatroom_pk):
    chatroom = get_object_or_404(ChatRoom, id=chatroom_pk)
    form = NewMessageForm()

    return render(request, 'shopmart/chatroom.html', {
        'chatroom': chatroom,
        'form': form,
        'title': 'ChatRoom',
    })


@login_required
def inbox(request):
    chatrooms = ChatRoom.objects.filter(members__in=[request.user.id]).annotate(latest_message_time=Max('messages__created_at')).order_by('-latest_message_time')

    return render(request, 'shopmart/inbox.html', {
        'chatrooms': chatrooms,
        'title': 'Inbox',
    })






# Payment views


class HomePageView(TemplateView):
    template_name = 'shopmart/payment/home.html'

class SuccessView(TemplateView):
    template_name = 'shopmart/success.html'

class CancelledView(TemplateView):
    template_name = 'shopmart/cancelled.html'


@csrf_exempt
def stripe_config(request):
    if request.method == 'GET':
        stripe_config = {'publicKey': settings.STRIPE_PUBLISHABLE_KEY}
        return JsonResponse(stripe_config, safe=False)


@csrf_exempt
@login_required
def create_checkout_session(request, product_pk):
    
    product = get_object_or_404(Product, pk=product_pk)

    if request.method == 'GET':
        domain_url = 'http://127.0.0.1:8000/shopmart/payment/'
        stripe.api_key = settings.STRIPE_SECRET_KEY

        if not product.is_reserved and not product.is_sold:
            try:
                checkout_session = stripe.checkout.Session.create(
                    client_reference_id=product.pk if request.user.is_authenticated else None,
                    success_url=domain_url + 'success?session_id={CHECKOUT_SESSION_ID}',
                    cancel_url=domain_url + 'cancelled/',
                    payment_method_types=['card'],
                    mode='payment',
                    line_items=[{
                        "price_data": {
                            "currency": 'usd',
                            "product_data": { "name": product.name,},
                            "unit_amount": int(product.price * 100),
                        },
                        "quantity": 1,
                    }]
                )
                # reserve the product
                product.reserve(request.user)
                # print('Product is reserved')

                return JsonResponse({'sessionId': checkout_session['id']})
            except Exception as e:
                return JsonResponse({'error': str(e)})
        else:
            return JsonResponse({'error': 'Product is already sold or reserved by another customer. Please refresh your page!'})


@csrf_exempt
def stripe_webhook(request):
    stripe.api_key = settings.STRIPE_SECRET_KEY
    endpoint_secret = settings.STRIPE_ENDPOINT_SECRET
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, endpoint_secret
        )
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return HttpResponse(status=400)
    
    # Handle the checkout.session.completed event
    if event['type'] == 'checkout.session.completed':
        print("Payment was successful.")

        # Get the Checkout session ID from the event
        session_id = event['data']['object']['id']

        # Find the product associated with this session
        
        checkout_session = stripe.checkout.Session.retrieve(session_id)
        product_pk = checkout_session.get('client_reference_id')
        
        if product_pk:
            # Mark the product as sold here
            product = Product.objects.get(pk=product_pk)
            product.is_reserved = False
            product.is_sold = True
            product.save()
            print("Product marked as sold.")
            print('Sold', product.is_sold)
            print('Reserved', product.is_reserved)

    return HttpResponse(status=200)




# browse views

def get_products(request):
    products_list = Product.objects.filter(is_sold=False).order_by('price')
    categories = Category.objects.all().order_by('name',)
    form = CategoryForm(request.GET)

    min_max_price = products_list.aggregate(Min('price'), Max('price'))

    query = request.GET.get('query', '')
    max_price = request.GET.get('max-price', None)

    if query:
        products_list = products_list.filter(Q(name__icontains=query) | Q(description__icontains=query))

    if max_price:

shopmart/templates/shopmart/about.html
{% extends 'shopmart/base.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
<div class="lg:w-4/5 xl:w-3/5 my-6 mx-auto p-6 bg-cyan-950 rounded-xl">
    <h1 class="mb-6 text-3xl text-center">About</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi, rerum? Voluptatem esse nesciunt est incidunt exercitationem, 
        laboriosam magni illum adipisci sint laudantium aut quibusdam maxime cum quae accusantium, pariatur corrupti. Lorem, ipsum dolor sit amet 
        consectetur adipisicing elit. Quisquam, temporibus quia? Consequuntur eius, quaerat optio quidem quos necessitatibus animi blanditiis possimus quis 
        error nemo eaque soluta sequi laudantium ut a.
    </p>

</div>
{% endblock %}

shopmart/templates/shopmart/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>

    <link href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css" rel="stylesheet">

    {% block head %} {% endblock %}
    <title>{% block title %}{% endblock %} | ShopMart</title>

    {% block style %} {% endblock %}
</head>
<body class="bg-cyan-900 text-white">

    <nav id="short_navbar" class="lg:hidden flex flex-col justify-start items-center"> 

        <div class="mt-5 mx-8 px-6 py-3 w-4/5 rounded-full bg-cyan-950 flex justify-between items-center rounded-full bg-cyan-950 ">
            <button id="menu_icon" class="scale-125 hover:scale-150 transition duration-300 ease-in-out" onclick="toggleMenu()"><i class="ri-menu-line"></i></button>
            <a href="{% url 'shopmart:index' %}" class="text-xl text-white font-semibold hover:scale-105 transition duration-300 ease-in-out">ShopMart</a>
        </div>    
        
        <div id="menu_list" class="absolute top-16 z-0 opacity-0 mt-5 mx-8 px-6 py-3 w-3/5 flex flex-col gap-5 items-center rounded-xl bg-cyan-950 shadow-lg transition-opacity duration-300 ease-in-out">
                <a href="{% url 'shopmart:browse' %}" class="w-32 text-center px-4 py-1 bg-cyan-800 rounded-full hover:bg-cyan-900 hover:scale-95 shadow-lg transition duration-300 ease-in-out">Browse</a>
                

                {% if request.user.is_authenticated %}
                <a href="{% url 'shopmart:new' %}" class="w-32 text-center px-4 py-1 bg-cyan-800 rounded-full hover:bg-cyan-900 hover:scale-95 shadow-lg transition duration-300 ease-in-out">List Item</a>
                <a href="{% url 'shopmart:inbox' %}" class="w-32 text-center px-4 py-1 bg-cyan-800 rounded-full hover:bg-cyan-900 hover:scale-95 shadow-lg transition duration-300 ease-in-out">Inbox</a>
                <a href="{% url 'shopmart:dashboard' %}" class="w-32 text-center px-4 py-1 bg-cyan-800 rounded-full hover:bg-cyan-900 hover:scale-95 shadow-lg transition duration-300 ease-in-out">Dashboard</a>
                {% endif %}

                {% if request.user.is_authenticated %}
                <a href="{% url 'core:logout' %}" class="w-32 text-center px-4 py-1 bg-red-500 text-white rounded-full hover:bg-red-700 hover:scale-95 shadow-lg transition duration-300 ease-in-out">Logout</a>
                {% else %}
                <a href="{% url 'core:login' %}" class="w-32 text-center px-4 py-1 bg-cyan-800 rounded-full hover:bg-cyan-900 hover:scale-95 shadow-lg transition duration-300 ease-in-out">LogIn</a>
                <a href="{% url 'core:signup' %}" class="w-32 text-center px-4 py-1 bg-cyan-800 rounded-full hover:bg-cyan-900 hover:scale-95 shadow-lg transition duration-300 ease-in-out">SignUp</a>
                {% endif %}
    
        </div>
    </nav>

    <nav id="long_navbar" class="mt-5 mx-8 px-6 py-3 justify-between items-center rounded-full bg-cyan-950 hidden lg:flex shadow-lg">
        <div class="w-1/3 flex justify-start ">
            <a href="{% url 'shopmart:index' %}" class="text-xl text-white font-semibold shadow-lg hover:scale-105 transition duration-300 ease-in-out">ShopMart</a>
        </div>

        <div class="w-1/3 whitespace-nowrap space-x-4 xl:space-x-8 flex justify-center">
            <a href="{% url 'shopmart:browse' %}" class="{% if request.path == '/shopmart/browse/' %} bg-cyan-900 scale-90 {% else %} bg-cyan-800 {% endif %} px-4 py-1 rounded-full hover:bg-cyan-900 hover:scale-90 shadow-lg transition duration-300 ease-in-out">Browse</a>
            
            {% if request.user.is_authenticated %}
            <a href="{% url 'shopmart:new' %}" class="{% if request.path == '/shopmart/products/new/' %} bg-cyan-900 scale-90 {% else %} bg-cyan-800 {% endif %} px-4 py-1 inline rounded-full hover:bg-cyan-900 hover:scale-90 shadow-lg transition duration-300 ease-in-out">List Item</a>
            <a href="{% url 'shopmart:inbox' %}" class="{% if request.path == '/shopmart/chat/inbox/' %} bg-cyan-900 scale-90 {% else %} bg-cyan-800 {% endif %} px-4 py-1 rounded-full hover:bg-cyan-900 hover:scale-90 shadow-lg transition duration-300 ease-in-out">Inbox</a>
            <a href="{% url 'shopmart:dashboard' %}" class="{% if request.path == '/shopmart/dashboard/' %} bg-cyan-900 scale-90 {% else %} bg-cyan-800 {% endif %} px-4 py-1 rounded-full hover:bg-cyan-900 hover:scale-90 shadow-lg transition duration-300 ease-in-out">Dashboard</a>
            
            {% endif %}
        </div>

        <div class="w-1/3 space-x-4 flex justify-end">
            {% if request.user.is_authenticated %}
            <p class="inline-block flex items-center text-sm text-cyan-900">LoggedIn As {{ request.user.username|upper }}</p>
            <a href="{% url 'core:logout' %}" class="px-4 py-1 bg-red-500 text-white rounded-full hover:bg-red-700 shadow-lg transition duration-300 ease-in-out">Logout</a>
            {% else %}
            <a href="{% url 'core:login' %}" class="px-4 py-1 bg-cyan-800 rounded-full hover:bg-cyan-900 shadow-lg transition duration-300 ease-in-out">LogIn</a>
            <a href="{% url 'core:signup' %}" class="px-4 py-1 bg-cyan-800 rounded-full hover:bg-cyan-900 shadow-lg transition duration-300 ease-in-out">SignUp</a>
            {% endif %}
        </div>
    </nav>

    <main id="main_content" class="w-full sm:w-4/5 lg:max-w-7xl mx-auto p-6 transition-transform ease-in-out duration-300">
        {% if messages %}
        <div class="message mb-4 w-max mx-auto mt-4 px-10 py-2 text-center bg-slate-800 rounded-full shadow-2xl">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        </div>
        {% endif %}

        {% block content %}

        {% endblock %}
    </main>

    <footer id="footer" class="px-6 py-6 flex justify-between border-gray-800 bg-cyan-950 transition-transform ease-in-out duration-300">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-300">About</h3>
            <p class="text-lg text-gray-400">Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam facilis assumenda, optio eius rerum vel tempora provident quam! Officiis non repellendus tempora. Aliquid, officia nobis facilis consectetur delectus minus sed.</p>
        </div>

        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-300">Menu</h3>
            <ul class="space-y-2">
                <li><a href=" {% url 'shopmart:about' %} " class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href=" {% url 'shopmart:contact' %} " class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                <li><a href=" {% url 'shopmart:policy' %} " class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                <li><a href=" {% url 'shopmart:terms' %} " class="text-lg text-teal-500 hover:text-teal-700">Terms of use</a></li>
            </ul>
        </div>
    </footer>

    <script>
        function toggleMenu () {
            var menuIconElement = document.getElementById('menu_list');
            var mainContentElement = document.getElementById('main_content');
            var footerElement = document.getElementById('footer');

            if (menuIconElement.classList.contains('opacity-0')) {
                menuIconElement.classList.remove('opacity-0');
                menuIconElement.classList.add('opacity-100');
            } else {
                menuIconElement.classList.add('opacity-0');
                menuIconElement.classList.remove('opacity-100')
            }

            mainContentElement.classList.toggle('translate-y-72'); // Push down
            footerElement.classList.toggle('translate-y-72')
            
        }
    </script>

    {% block scripts %}

    {% endblock %}

</body>
</html>

shopmart/templates/shopmart/detail.html
{% extends 'shopmart/base.html' %}

{% load static %} <!-- payment -->

{% block title %} {{ product.name }} {% endblock %}

{% block head %}
<script src="https://js.stripe.com/v3/"></script>
<script src="{% static 'shopmart/payment/stripe.js' %}"></script>   <!-- new -->
{% endblock %}

{% block content %}
    <div class="flex flex-col md:flex-row gap-5 justify-evenly">

        {% if product.image %}
        <div class="w-full h-[600px] md:w-3/5 rounded-xl overflow-hidden border-8 border-cyan-950"> 
            <img src="{{ product.image.url }}" class="w-full h-full object-cover">
        </div>
        {% else %}
        <div class="w-full h-[600px] md:w-3/5 rounded-xl overflow-hidden border-8 border-cyan-950"> 
            <h1 class="w-full h-full flex justify-center items-center text-gray-300">No image available</h1>
        </div>
        {% endif %}

        <div class="w-full md:w-2/5 p-6 bg-cyan-950 rounded-xl">
            <h1 class="mb-6 text-3xl font-bold text-cyan-500">{{ product.name }}</h1>
            <p class="text-gray-300 text-xl font-semibold">Price: ${{ product.price }}</p>
            <p class="text-gray-300 text-lg font-semibold">Seller: {{ product.created_by.username }}</p>

        {% if product.description %}
            <p class="text-gray-500">Description: {{ product.description }}<strong class="text-gray-500"></strong></p>
        {% endif %}
        {% if product.is_sold %}
            <p class="text-3xl font-bold text-gray-500">SOLD</p>
        {% endif %}
        {% if product.is_reserved %}
            <p class="text-gray-700"><strong class="text-gray-500">This product is reserved and awaiting for payment.</strong></p>
        {% endif %}

        {% if request.user.is_authenticated %}

        {% if product.created_by == request.user %}
            <a href="{% url 'shopmart:edit' product.id %}" class="inline-block mt-6 px-6 py-1 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700 transition duration-300 ease-in-out">Edit</a>
            <a href="{% url 'shopmart:delete' product.id %}" class="inline-block mt-6 px-6 py-1 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700 transition duration-300 ease-in-out">Delete</a>
        {% else %}
            <a href="{% url 'shopmart:new-chatroom' product.id %}" class="inline-block mt-6 px-6 py-1 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700 transition duration-300 ease-in-out">Contact Seller</a>
            <button id="submitBtn" product-pk="{{product.id}}" class="inline-block mt-6 px-6 py-1 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700 transition duration-300 ease-in-out {% if product.is_sold or product.is_reserved %} bg-gray-400 pointer-events-none {% endif %}">Purchase</button>
        {% endif %}

        {% else %}
            <h1 class="mt-5 text-xl font-bold text-cyan-500">Please log in to edit, delete and purchase product!!</h1>
        {% endif %}
        </div>
    </div>

    <div class="mt-6 px-5 py-12 bg-cyan-950 rounded-xl">
        <h2 class="mb-12 text-3xl font-semibold text-center">Related products</h2>
        <div class="flex flex-col md:flex-row md:flex-wrap gap-5 justify-evenly items-center">
            {% for product in related_products %}
                    <a href="{% url 'shopmart:detail' product.id %}" class="w-96 hover:scale-105 transition duration-300 ease-in-out">
                        <div class="w-full h-80 rounded-t-xl overflow-hidden">
                            <img src="{{ product.image.url }}" alt="product-image" class="w-full h-full object-cover">
                        </div>
                        <div class="p-6 bg-cyan-900 rounded-b-xl">
                            <h2 class="text-2xl font-semibold text-cyan-500">{{ product.name }}</h2>
                            <p class="text-black">${{ product.price }}</p>
                        </div>
                    </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}